// src/components/layout/Sidebar.jsx
import { Link, useLocation, useNavigate } from "react-router-dom";
import { 
  LayoutDashboard, 
    Car, 
      History, 
        BarChart3, 
          UserRound, 
            ParkingSquare,
              Users,
                LogOut,
                  Clock,
                    Settings,
                      Tv,
                        Database,
                          ChevronDown
                          } from "lucide-react";
                          import { useEffect, useState } from "react";
                          import { useAuth } from "../../hooks/useAuth";
                          import BackupButton from "../BackupButton";
                          import RestoreButton from "../RestoreButton";

                          const menuItems = [
                            { path: "/", icon: LayoutDashboard, label: "Dashboard", adminOnly: false },
                              { path: "/vehicles", icon: Car, label: "Vehículos dentro", adminOnly: false },
                                { path: "/history", icon: History, label: "Historial", adminOnly: false },
                                  { path: "/reports", icon: BarChart3, label: "Reportes", adminOnly: false },
                                    { path: "/doctors", icon: UserRound, label: "Médicos", adminOnly: false },
                                      { path: "/parking", icon: ParkingSquare, label: "Parking Virtual", adminOnly: false },
                                        { path: "/parking-history", icon: History, label: "Historial Estacionamiento", adminOnly: false },
                                          { path: "/users", icon: Users, label: "Usuarios", adminOnly: true },
                                          ];

                                          const systemItems = [
                                            { path: "/tv", icon: Tv, label: "Modo TV", adminOnly: true },
                                              { path: "/logs", icon: Database, label: "Logs del sistema", adminOnly: true },
                                              ];

                                              export default function Sidebar({ onClose }) {
                                                const location = useLocation();
                                                  const navigate = useNavigate();
                                                    const { user, isAdmin } = useAuth();
                                                      const [systemOpen, setSystemOpen] = useState(false);

                                                        const handleLogout = () => {
                                                            localStorage.removeItem("user");
                                                                navigate("/login");
                                                                    if (onClose) onClose();
                                                                      };

                                                                        const handleLinkClick = () => {
                                                                            if (onClose) onClose();
                                                                              };

                                                                                const filteredMenuItems = menuItems.filter(item => !item.adminOnly || isAdmin);
                                                                                  const filteredSystemItems = systemItems.filter(item => !item.adminOnly || isAdmin);

                                                                                    return (
                                                                                        <aside className="w-72 bg-slate-900 border-r border-slate-800 flex flex-col h-full">
                                                                                              {/* Logo */}
                                                                                                    <div className="p-5 border-b border-slate-800 flex items-center justify-center">
                                                                                                            <div className="logo-universal">
                                                                                                                      <img src="/logo.png" alt="Logo" />
                                                                                                                              </div>
                                                                                                                                    </div>

                                                                                                                                          {/* Capacidad y usuario */}
                                                                                                                                                <div className="px-5 py-4 border-b border-slate-800">
                                                                                                                                                        <p className="text-sm font-semibold text-amber-500 mb-3">Capacidad total: 37 plazas</p>
                                                                                                                                                                
                                                                                                                                                                        <div className="space-y-2">
                                                                                                                                                                                  <p className="text-base text-slate-400">
                                                                                                                                                                                              Rol: <span className="text-white font-medium">{user?.rol || "Admin"}</span>
                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                  <p className="text-base text-slate-400">
                                                                                                                                                                                                                              Bienvenido, <span className="text-white font-medium">{user?.nombre || "Administrador"}</span>
                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                  <p className="text-sm text-slate-500 flex items-center gap-1">
                                                                                                                                                                                                                                                              <Clock className="w-3 h-3" />
                                                                                                                                                                                                                                                                          Sesión activa
                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                        {/* Menú */}
                                                                                                                                                                                                                                                                                                              <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
                                                                                                                                                                                                                                                                                                                      {filteredMenuItems.map((item) => {
                                                                                                                                                                                                                                                                                                                                const Icon = item.icon;
                                                                                                                                                                                                                                                                                                                                          const isActive = location.pathname === item.path;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                                                                        key={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                      to={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleLinkClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                  isActive 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "bg-amber-500/10 text-amber-400" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "text-slate-400 hover:bg-slate-800 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Icon className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-base">{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Sistema */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isAdmin && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="border-t border-slate-800 my-3"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setSystemOpen(!systemOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full flex items-center justify-between px-4 py-3 rounded-lg text-slate-400 hover:bg-slate-800 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Settings className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-base font-medium">Sistema</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ChevronDown className={`w-4 h-4 transition-transform duration-200 ${systemOpen ? 'rotate-180' : ''}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {systemOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="ml-7 space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {filteredSystemItems.map((item) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const Icon = item.icon;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const isActive = location.pathname === item.path;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleLinkClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`flex items-center gap-3 px-4 py-2 rounded-lg transition-all duration-200 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isActive 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? "bg-amber-500/10 text-amber-400" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "text-slate-400 hover:bg-slate-800 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Icon className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-base">{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="pl-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <BackupButton />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <RestoreButton />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Cerrar sesión */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-4 border-t border-slate-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full flex items-center justify-center gap-2 px-4 py-3 text-base text-red-400 hover:bg-red-500/10 rounded-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <LogOut className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Cerrar sesión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }