// src/components/layout/Sidebar.jsx
import { Link, useLocation, useNavigate } from "react-router-dom";
import { 
  LayoutDashboard, 
    Car, 
      History, 
        BarChart3, 
          UserRound, 
            ParkingSquare,
              Users,
                LogOut,
                  Clock
                  } from "lucide-react";
                  import { useEffect, useState } from "react";

                  const menuItems = [
                    { path: "/", icon: LayoutDashboard, label: "Dashboard" },
                      { path: "/vehicles", icon: Car, label: "Vehículos dentro" },
                        { path: "/history", icon: History, label: "Historial" },
                          { path: "/reports", icon: BarChart3, label: "Reportes" },
                            { path: "/doctors", icon: UserRound, label: "Médicos" },
                              { path: "/parking", icon: ParkingSquare, label: "Parking Virtual" },
                                { path: "/parking-history", icon: History, label: "Historial Estacionamiento" },
                                  { path: "/users", icon: Users, label: "Usuarios" },
                                  ];

                                  export default function Sidebar() {
                                    const location = useLocation();
                                      const navigate = useNavigate();
                                        const [user, setUser] = useState(null);

                                          useEffect(() => {
                                              const userData = localStorage.getItem("user");
                                                  if (userData) {
                                                        try {
                                                                setUser(JSON.parse(userData));
                                                                      } catch (e) {}
                                                                          }
                                                                            }, []);

                                                                              const handleLogout = () => {
                                                                                  localStorage.removeItem("user");
                                                                                      navigate("/login");
                                                                                        };

                                                                                          return (
                                                                                              <aside className="w-64 bg-slate-900 border-r border-slate-800 flex flex-col h-screen">
                                                                                                    {/* Capacidad y datos del usuario */}
                                                                                                          <div className="p-5 border-b border-slate-800">
                                                                                                                  <p className="text-xs font-semibold text-amber-500 mb-3">Capacidad total: 37 plazas</p>
                                                                                                                          
                                                                                                                                  <div className="space-y-1">
                                                                                                                                            <p className="text-sm text-slate-400">
                                                                                                                                                        Rol: <span className="text-white">{user?.rol || "Admin"}</span>
                                                                                                                                                                  </p>
                                                                                                                                                                            <p className="text-sm text-slate-400">
                                                                                                                                                                                        Bienvenido, <span className="text-white">{user?.nombre || "Administrador"}</span>
                                                                                                                                                                                                  </p>
                                                                                                                                                                                                            <p className="text-xs text-slate-500 flex items-center gap-1">
                                                                                                                                                                                                                        <Clock className="w-3 h-3" />
                                                                                                                                                                                                                                    Sesión activa
                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                  {/* Menú de navegación */}
                                                                                                                                                                                                                                                                        <nav className="flex-1 p-4 space-y-1">
                                                                                                                                                                                                                                                                                {menuItems.map((item) => {
                                                                                                                                                                                                                                                                                          const Icon = item.icon;
                                                                                                                                                                                                                                                                                                    const isActive = location.pathname === item.path;
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                  key={item.path}
                                                                                                                                                                                                                                                                                                                                                                to={item.path}
                                                                                                                                                                                                                                                                                                                                                                              className={`flex items-center gap-3 px-3 py-2 rounded-lg transition-all duration-200 ${
                                                                                                                                                                                                                                                                                                                                                                                              isActive 
                                                                                                                                                                                                                                                                                                                                                                                                                ? "bg-amber-500/10 text-amber-400" 
                                                                                                                                                                                                                                                                                                                                                                                                                                  : "text-slate-400 hover:bg-slate-800 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Icon className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-sm">{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Cerrar sesión */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-4 border-t border-slate-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full flex items-center justify-center gap-2 px-4 py-2 text-sm text-red-400 hover:bg-red-500/10 rounded-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <LogOut className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Cerrar sesión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }