// src/components/layout/Sidebar.jsx
import { Link, useLocation, useNavigate } from "react-router-dom";
import { 
  LayoutDashboard, 
    Car, 
      History, 
        BarChart3, 
          UserRound, 
            ParkingSquare,
              Users,
                LogOut,
                  Clock,
                    X,
                      Settings,
                        Tv,
                          Database,
                            ChevronDown,
                              Activity
                              } from "lucide-react";
                              import { useState } from "react";
                              import { useAuth } from "../../hooks/useAuth";
                              import BackupButton from "../BackupButton";
                              import RestoreButton from "../RestoreButton";

                              // Menús principales
                              const menuItems = [
                                { path: "/", icon: LayoutDashboard, label: "Dashboard", adminOnly: false },
                                  { path: "/vehicles", icon: Car, label: "Vehículos dentro", adminOnly: false },
                                    { path: "/history", icon: History, label: "Historial", adminOnly: false },
                                      { path: "/reports", icon: BarChart3, label: "Reportes", adminOnly: false },
                                        { path: "/doctors", icon: UserRound, label: "Médicos", adminOnly: false },
                                          { path: "/parking", icon: ParkingSquare, label: "Parking Virtual", adminOnly: false },
                                            { path: "/parking-history", icon: History, label: "Historial Estacionamiento", adminOnly: false },
                                              { path: "/users", icon: Users, label: "Usuarios", adminOnly: true },
                                                { path: "/logs", icon: Activity, label: "Logs", adminOnly: true },
                                                  { path: "/tv", icon: Tv, label: "Modo TV", adminOnly: true },
                                                  ];

                                                  const systemTools = [
                                                    { icon: Database, label: "Backup", component: BackupButton },
                                                      { icon: Activity, label: "Logs", component: null },
                                                        { icon: Tv, label: "Modo TV", component: null },
                                                        ];

                                                        export default function Sidebar({ onClose }) {
                                                          const location = useLocation();
                                                            const navigate = useNavigate();
                                                              const { user, isAdmin } = useAuth();
                                                                const [systemOpen, setSystemOpen] = useState(false);
                                                                  const [hoveredItem, setHoveredItem] = useState(null);

                                                                    const handleLogout = () => {
                                                                        localStorage.removeItem("user");
                                                                            navigate("/login");
                                                                                if (onClose) onClose();
                                                                                  };

                                                                                    const handleLinkClick = () => {
                                                                                        if (onClose) onClose();
                                                                                          };

                                                                                            // Filtrar menús según rol
                                                                                              const filteredMenuItems = menuItems.filter(item => !item.adminOnly || isAdmin);

                                                                                                return (
                                                                                                    <aside className="w-64 bg-slate-900 border-r border-slate-800 flex flex-col h-screen overflow-y-auto">
                                                                                                          {/* Botón cerrar para móvil */}
                                                                                                                <div className="flex justify-end p-3 lg:hidden border-b border-slate-800 sticky top-0 bg-slate-900 z-10">
                                                                                                                        <button onClick={onClose} className="p-1 rounded-lg bg-slate-800 text-white">
                                                                                                                                  <X className="w-5 h-5" />
                                                                                                                                          </button>
                                                                                                                                                </div>

                                                                                                                                                      {/* Logo */}
                                                                                                                                                            <div className="px-5 py-3 border-b border-slate-800 flex items-center justify-center">
                                                                                                                                                                    <div className="logo-universal">
                                                                                                                                                                              <img src="/logo.png" alt="Logo" />
                                                                                                                                                                                      </div>
                                                                                                                                                                                            </div>

                                                                                                                                                                                                  {/* Información del usuario */}
                                                                                                                                                                                                        <div className="px-5 pt-4 pb-3 border-b border-slate-800">
                                                                                                                                                                                                                <p className="text-xs font-semibold text-amber-500 mb-3">Capacidad total: 37 plazas</p>
                                                                                                                                                                                                                        <div className="space-y-1">
                                                                                                                                                                                                                                  <p className="text-sm text-slate-400">
                                                                                                                                                                                                                                              <span className="text-white">Rol:</span> {user?.rol || "Usuario"}
                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                  <p className="text-sm text-slate-400">
                                                                                                                                                                                                                                                                              <span className="text-white">Bienvenido,</span> {user?.nombre || "Usuario"}
                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                  <p className="text-xs text-slate-500 flex items-center gap-1">
                                                                                                                                                                                                                                                                                                              <Clock className="w-3 h-3" />
                                                                                                                                                                                                                                                                                                                          Sesión activa
                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                        {/* Menú de navegación */}
                                                                                                                                                                                                                                                                                                                                                              <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
                                                                                                                                                                                                                                                                                                                                                                      {filteredMenuItems.map((item) => {
                                                                                                                                                                                                                                                                                                                                                                                const Icon = item.icon;
                                                                                                                                                                                                                                                                                                                                                                                          const isActive = location.pathname === item.path;
                                                                                                                                                                                                                                                                                                                                                                                                    const isHovered = hoveredItem === item.path;
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                to={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleLinkClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onMouseEnter={() => setHoveredItem(item.path)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onMouseLeave={() => setHoveredItem(null)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`flex items-center justify-between group px-3 py-2 rounded-lg transition-all duration-200 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isActive 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "bg-amber-500/10 text-amber-400" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : "text-slate-400 hover:bg-slate-800 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } ${isHovered ? "translate-x-1" : ""}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Icon className={`w-5 h-5 transition-all duration-200 ${isHovered ? "scale-110 text-amber-400" : ""}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-sm">{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ChevronDown className={`w-4 h-4 transition-all duration-200 ${isActive ? "opacity-100 text-amber-400" : "opacity-0 group-hover:opacity-100"} ${isHovered ? "rotate-180" : ""}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Sección Sistema - solo visible para admin */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isAdmin && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="border-t border-slate-800 my-3"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setSystemOpen(!systemOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full flex items-center justify-between px-3 py-2 rounded-lg text-slate-400 hover:bg-slate-800 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Settings className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-sm font-medium">Sistema</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ChevronDown className={`w-4 h-4 transition-transform duration-200 ${systemOpen ? 'rotate-180' : ''}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {systemOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="ml-6 space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to="/tv"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleLinkClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-400 hover:bg-slate-800 hover:text-white transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Tv className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-sm">Modo TV</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                to="/logs"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={handleLinkClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-400 hover:bg-slate-800 hover:text-white transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Database className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-sm">Logs del sistema</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <BackupButton />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <RestoreButton />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Cerrar sesión */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-4 border-t border-slate-800 sticky bottom-0 bg-slate-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full flex items-center justify-center gap-2 px-4 py-2 text-sm text-red-400 hover:bg-red-500/10 rounded-lg transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <LogOut className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Cerrar sesión
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }