// src/pages/parking/ParkingPage.jsx
import { useEffect } from "react";
import { supabase } from "../../services/supabase";

export default function ParkingPage() {
  useEffect(() => {
      loadParking();
        }, []);

          async function loadParking() {
              const { data } = await supabase.from("parking_assignments").select("*");
                  renderizarParking(data || []);
                      actualizarStats(data || []);
                        }

                          // Lista de lugares que deben ser INVISIBLES (existen pero no se ven)
                            const lugaresInvisibles = [
                                "Z7", "Z8", "Z9", "Z10", "Z11",
                                    "W1", "W4", "W5", "W6", "W7",
                                        "T1", "T4", "T5", "T6", "T7"
                                          ];

                                            function esLugarInvisible(lugar) {
                                                return lugaresInvisibles.includes(lugar);
                                                  }

                                                    function renderizarParking(spots) {
                                                        const colS = document.getElementById("col-s");
                                                            const colZ = document.getElementById("col-z");
                                                                const colW = document.getElementById("col-w");
                                                                    const colT = document.getElementById("col-t");
                                                                        const bottomXY = document.getElementById("bottom-xy");

                                                                            // TODOS los lugares (incluyendo los invisibles)
                                                                                const lugaresS = ["S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","S11","S12","S13","S14"];
                                                                                    const lugaresZ = ["Z1","Z2","Z3","Z4","Z5","Z6","Z7","Z8","Z9","Z10","Z11","Z12","Z13","Z14"];
                                                                                        const lugaresW = ["W1","W2","W3","W4","W5","W6","W7","W8","W9","W10","W11","W12","W13"];
                                                                                            const lugaresT = ["T1","T2","T3","T4","T5","T6","T7","T8","T9","T10","T11","T12","T13"];
                                                                                                const lugaresXY = ["X1","X2"];

                                                                                                    const spotsMap = {};
                                                                                                        spots.forEach(spot => { spotsMap[spot.lugar] = spot; });

                                                                                                            if (colS) renderColumna(colS, lugaresS, spotsMap);
                                                                                                                if (colZ) renderColumna(colZ, lugaresZ, spotsMap);
                                                                                                                    if (colW) renderColumna(colW, lugaresW, spotsMap);
                                                                                                                        if (colT) renderColumna(colT, lugaresT, spotsMap);
                                                                                                                            if (bottomXY) renderColumna(bottomXY, lugaresXY, spotsMap);
                                                                                                                              }

                                                                                                                                function renderColumna(container, lugares, spotsMap) {
                                                                                                                                    if (!container) return;
                                                                                                                                        container.innerHTML = "";
                                                                                                                                            
                                                                                                                                                lugares.forEach(lugar => {
                                                                                                                                                      const spot = spotsMap[lugar];
                                                                                                                                                            const invisible = esLugarInvisible(lugar);
                                                                                                                                                                  const ocupado = spot?.activo || false;
                                                                                                                                                                        const esJunta = spot?.tipo_medico === "Junta";
                                                                                                                                                                              
                                                                                                                                                                                    const div = document.createElement("div");
                                                                                                                                                                                          
                                                                                                                                                                                                if (invisible) {
                                                                                                                                                                                                        // Lugar invisible: existe pero no se ve, ocupa espacio
                                                                                                                                                                                                                div.className = "parking-spot invisible-spot";
                                                                                                                                                                                                                        div.style.visibility = "hidden";
                                                                                                                                                                                                                                div.style.opacity = "0";
                                                                                                                                                                                                                                        div.style.pointerEvents = "none";
                                                                                                                                                                                                                                                div.style.height = "70px";
                                                                                                                                                                                                                                                        div.innerHTML = `<span class="spot-number" style="visibility:hidden">${lugar}</span>`;
                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                      // Lugar normal visible
                                                                                                                                                                                                                                                                              div.className = `parking-spot ${ocupado ? (esJunta ? "junta" : "occupied") : "free"}`;
                                                                                                                                                                                                                                                                                      div.setAttribute("data-lugar", lugar);
                                                                                                                                                                                                                                                                                              if (ocupado) div.setAttribute("data-tooltip", spot.medico_nombre || "");
                                                                                                                                                                                                                                                                                                      div.onclick = () => alert(`Lugar ${lugar} - ${ocupado ? `Ocupado por ${spot.medico_nombre}` : "Libre"}`);
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                      div.innerHTML = `
                                                                                                                                                                                                                                                                                                                                <span class="spot-number">${lugar}</span>
                                                                                                                                                                                                                                                                                                                                          ${ocupado ? `<div class="spot-doctor"><i class="fas fa-user-md"></i> ${(spot.medico_nombre || "").split(" ")[0] || "Dr"}</div>` : ""}
                                                                                                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                    container.appendChild(div);
                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                            function actualizarStats(spotsData) {
                                                                                                                                                                                                                                                                                                                                                                                const ocupados = spotsData.filter(s => s.activo).length;
                                                                                                                                                                                                                                                                                                                                                                                    const libres = spotsData.length - ocupados;
                                                                                                                                                                                                                                                                                                                                                                                        const porcentaje = spotsData.length > 0 ? Math.round((ocupados / spotsData.length) * 100) : 0;
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                const libresEl = document.getElementById("libresCount");
                                                                                                                                                                                                                                                                                                                                                                                                    const ocupadosEl = document.getElementById("ocupadosCount");
                                                                                                                                                                                                                                                                                                                                                                                                        const porcentajeEl = document.getElementById("porcentajeCount");
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                if (libresEl) libresEl.innerText = libres;
                                                                                                                                                                                                                                                                                                                                                                                                                    if (ocupadosEl) ocupadosEl.innerText = ocupados;
                                                                                                                                                                                                                                                                                                                                                                                                                        if (porcentajeEl) porcentajeEl.innerText = `${porcentaje}%`;
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                            function scrollToCol(colId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById(colId)?.scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                    function scrollToBottom() {
                                                                                                                                                                                                                                                                                                                                                                                                                                        window.scrollTo({ behavior: "smooth", top: document.body.scrollHeight });
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                            function aplicarFiltro(filtro) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("Filtro:", filtro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div id="parkingVirtualSection" className="page-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Header */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="parking-header-premium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="parking-title-premium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="logo-universal" style={{ margin: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src="/seguridad.png" alt="Logo" style={{ height: "45px" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>Parking Virtual</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Distribución en tiempo real</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="stats-modernas">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="stat-icon">🟢</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="stat-value" id="libresCount">0</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="stat-label">Libres</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="stat-icon">🔴</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="stat-value" id="ocupadosCount">0</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="stat-label">Ocupados</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="stat-icon">📊</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="stat-value" id="porcentajeCount">0%</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="stat-label">Ocupación</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Mini-mapa */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mini-map">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mini-spot" onClick={() => scrollToCol('col-s')}>S</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mini-spot" onClick={() => scrollToCol('col-z')}>Z</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mini-spot" onClick={() => scrollToCol('col-w')}>W</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mini-spot" onClick={() => scrollToCol('col-t')}>T</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mini-spot" onClick={() => scrollToBottom()}>X/Y</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Filtros */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="filtros-rapidos">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="filtro-btn active" onClick={() => aplicarFiltro('todos')}>🎯 Todos</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="filtro-btn" onClick={() => aplicarFiltro('medicos')}>👨‍⚕️ Médicos</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="filtro-btn" onClick={() => aplicarFiltro('junta')}>🏛️ Junta</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="filtro-btn" onClick={() => aplicarFiltro('libres')}>🟢 Libres</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="filtro-btn" onClick={() => aplicarFiltro('ocupados')}>🔴 Ocupados</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Mapa */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="parking-map-premium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="parking-title-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="col-label">S</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="col-label">Z</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="col-label">W</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="col-label">T</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="parking-columns">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="parking-col" id="col-s"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="parking-col" id="col-z"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="parking-col" id="col-w"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="parking-col" id="col-t"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="parking-bottom-premium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bottom-label">📍 LUGARES ESPECIALES</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bottom-spots" id="bottom-xy"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Leyenda */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="parking-legend-premium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="legend-item"><span className="legend-box free-box"></span> Libre</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="legend-item"><span className="legend-box occupied-box"></span> Ocupado</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="legend-item"><span className="legend-box junta-box"></span> Junta Directiva</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="legend-item"><i className="fas fa-arrows-alt"></i> Click para asignar</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }